version: '3'

services:
  dev-web:
    build:
      context: .
      dockerfile: ./frontend/dev.dockerfile
    volumes:
      - '.:/project'
    working_dir: /project/frontend
    entrypoint: npm start
    ports:
      - '0.0.0.0:1337:1337'
  backend:
    build:
      context: ./backend-nodejs
      dockerfile: backend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - JIRA_BASE_URL=https://jira.truststack.us
      - JIRA_EMAIL=your-email@example.com
      - JIRA_API_TOKEN=your-api-token
